### ISSUE TITLE
인증 로직 리팩토링 및 추가 구현 및 OAuth 2.0 설정 추가

### ISSUE THREAD

**Issue by choidongkuen** [depromeet/teum-teum-server#31]
## 기능
인증 로직에 대한 코드 리팩토링을 진행하며, 누락된 기능을 추가 구현합니다.
## Todo
- [x] JwtAuthenticationFilter 코드 리팩토링
- [x] 카카오, 네이버 OAuth2.0 설정 추가
- [x] 불필요한 주석 제거
- [x] 테스트
