### ISSUE TITLE
feat: 모임 참여 취소 API

### ISSUE THREAD

**Issue by ddingmin** [depromeet/teum-teum-server#33]
## 기능
유저가 참여 신청한 모임을 취소한다.

## Todo
- [ ] 유저가 참여했던 모임에 취소한다.
  - [ ] 유저가 참여하지 않은 경우의 예외를 처리한다.
  - [ ] 유저가 Host인 경우의 예외를 처리한다.
  - [ ] 유저가 종료된 모임을 취소하려는 예외를 처리한다.
