### ISSUE TITLE
feat: 유저 도메인 작성

### ISSUE THREAD

**Issue by devxb** [depromeet/teum-teum-server#4]
## 기능
유저 도메인을 개발한다

## Todo
- [ ] 유저 엔티티 작성
- [ ] 유저 레포지토리 작성
- [ ] 도메인 통신 서비스 작성
