### ISSUE TITLE
feat: 위치 기반 API 구현 및 테스트

### ISSUE THREAD

**Issue by choidongkuen** [depromeet/teum-teum-server#91]
## 기능
위치 기반 API 구현 
## Todo
- [x] 유저 위치 도메인 구성
- [x] 기타 코드(ex 위치 계산 등) 구현
- [x] 필요한 의존성 추가
